### ISSUE TITLE
Comment may be wrong?

### ISSUE THREAD

**Issue by jintrone** [jintrone/ContextualizedContagion#1]
https://github.com/jintrone/ContextualizedContagion/blob/340667bee2aa0090c6897dfa3618025a21da4ea7/scripts/AgentClass.py#L76

Just reading through the code to make sure I understand - I think the global variable will be NaN if no neighbors have the bit and global is set to "local" correct?  I think we should probably change this to better describe what's going on.  I keep getting confused!  Let's instead call this parameter to "contagion_mode" and the states can be "viral" (meaning one of my neighbors must have the state in order for me to get it) or "opinion" (meaning I can flip that bit regardless of my neighbors)

**Comment by nsitaula** [comment]
yes, I think it is confusing I will change the variable name to "contagion_mode". So, if no neighbors have the bit and set to viral then it cannot change the bit whereas, it could change bits if (i) no neighbors have the bit and set to "opinion" or (ii) if some neighbors have the bit irrespective of "opinion" or "viral" set to the variable "contagion_mode".

**Comment by jintrone** [comment]
Precisely!  Thanks.

On Aug 19, 2019, at 5:41 PM, Niraj <notifications@github.com<mailto:notifications@github.com>> wrote:


yes, I think it is confusing I will change the variable name to "contagion_mode". So, if no neighbors have the bit and set to viral then it cannot change the bit whereas, it could change bits if (i) no neighbors have the bit and set to "opinion" or (ii) if some neighbors have the bit irrespective of "opinion" or "viral" set to the variable "contagion_mode".
